services:
    myservice:
        build: ./.devcontainer
        container_name: enka-network-userscript
        working_dir: /workspace
        volumes:
            # node_modulesディレクトリはホスト側に渡さないようにDockerのvolume内に格納
            - ./:/workspace
            - node-modules:/workspace/node_modules
        tty: true

volumes:
    node-modules:
