@startuml {artifact.png}
title 聖遺物

class "聖遺物セット" as ArtifactSet {
    # artifacts: Artifact []
}
class "聖遺物" as Artifact {
    # mainStat: MainStat
    # subStat: SubStats
}
class "メインオプション" as MainStat {
    # statName: string
    # stat: number
    # level: number
}
class "サブオプションセット" as SubStats {
    # subStat: SubStat
    --
    + eachRollValue(...statName: string): number
    + sumRollValue(...statName: string): number
}
class "サブオプション" as SubStat {
    # statName: string
    # stat: number
    # statRolls: StatRolls
}
class StatRolls {
    # rollList: StatRoll[]
    --
    + sumRollValue(): number
    + eachRollValue(): number
}
class StatRoll {
    # roll: number
    --
    + rollValue(): number
}

ArtifactSet "0..5" o-- "1" Artifact
Artifact o-- MainStat
Artifact o-- SubStats
SubStats "0..4" o-- SubStat
SubStat "1" o-- "1" StatRolls
StatRolls "0..6" o-- "1" StatRoll

@enduml